#!/usr/bin/env bash
# use script to create a file containing it's PID"

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' 15

trap 'echo "Y U no love me?!";' 2

trap 'rm -f /var/run/myscript.pid; echo "Terminating..."; exit' 3

while true; do
    echo "To infinity and beyond"
    sleep 2
done

