#!/usr/bin/env bash
# init bash script
PID_FILE=/var/run/my_process.pid
PROCESS_SCRIPT=./manage_my_process

case "$1" in
    start)
        if [ -f "$PID_FILE" ]; then
            echo "manage_my_process is already running."
        else
            $PROCESS_SCRIPT &
            echo $! > "$PID_FILE"
            echo "manage_my_process started"
        fi
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
            kill -9 "$(cat "$PID_FILE")"
            rm -f "$PID_FILE"
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running."
        fi
        ;;
    restart)
        if [ -f "$PID_FILE" ]; then
            kill -9 "$(cat "$PID_FILE")"
            rm -f "$PID_FILE"
        fi
        $PROCESS_SCRIPT &
        echo $! > "$PID_FILE"
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac

