#!/usr/bin/env bash
# This should print "Best school" 10 times using while loop but adds Hi on a new line when it reaches the 9th iteration

var="Best School"
var2="Hi"
i="0"
while [ $i -lt 10 ]; do
    if [ $i -eq 9 ]; then
        echo "$var2"
    fi
    echo "$var"
 ((i++))
done
