#!/usr/bin/env bash
# This should print "Best school" 10 times using while loop

var="Best School"
var1="bad luck"
var2="good luck"
i="1"
while [ $i -le 10 ]; do
    if [ $i -eq 4 ]; then
        echo "$var1"
    elif [ $i -eq 8 ]; then
        echo "$var2"
    else
        echo "$var"
    fi
 ((i++))
done
