#!/usr/bin/env bash
# This should display different stings with the while loop and case statement


var1="bad luck from China"
var2="bad luck from Japan"
var3="bad luck from Italy"
i="1"
while [ $i -le 20 ]; do
    case $i in
            4)
                echo "$i" && echo "$var1"
                ;;
            9)
                echo "$i" && echo "$var2"
                ;;
            17)
                echo "$i" && echo "$var3"
                ;;
            *)
                echo "$i"
                ;;
    esac

((i++))
done
